# Generated by Django 4.0.2 on 2022-02-22 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='type',
            field=models.CharField(default='null', max_length=10),
        ),
    ]
